### ISSUE TITLE
Console Menu doesn't error handle properly

### ISSUE THREAD

**Issue by BitBangingBytes** [beroset/pico-puller#1]
When entering text to select a menu item, if you misspell a word or enter something not shown such as "hel" instead of "help" the program becomes non-responsive and the only way to get it back is to reboot.

**Comment by beroset** [comment]
Can you elaborate a bit more on how you're connecting and when this happens?  Here's what I get when using the `pico-puller` script:
```
$ pico-puller 
Connecting to pico, exit with ~.
sta
That is not a valid choice.
stat
That is not a valid choice.
statu
That is not a valid choice.
status
SRD = 0x0, SRD1 = 0x0
> 
```

**Comment by BitBangingBytes** [comment]
Connecting over USB on a Mac using minicom with the following command line. Also note I had to turn local echo ON as no key presses were displayed on screen.

minicom -b 115200 -o -D /dev/usb.xyz

**Comment by beroset** [comment]
Is it possible for you to use the `expect` script?  I know it's available for the Mac, but I don't have a functioning Mac right now.  (Charger on order.)  It might help narrow down the problem.

**Comment by beroset** [comment]
It's a `minicom` issue.  It works just fine with the `pico-puller` script and with `cutecom` but unlike those, `minicom` does not buffer a line before sending, so every keystroke is sent verbatim.  This has a few effects.  First, editing a line doesn't work so hitting the backspace character, for example, sends a literal `DEL` or `BS` character.  That does no harm, but it also doesn't help.  For this issue, it means that you should configure `minicom` not to add carriage return or line feed, but to use a translation.  Specifically, under configuration (ctrl-A O) "Screen and keyboard" choose "P - Character conversion" and for character code 13 (carriage return) change the output to 10 (line feed).  This will then send a linefeed character (`LF`) whenever you hit the Enter key and `pico-puller` will no longer seem to hang.
